import 'package:flutter/material.dart';
import '../models/student.dart';
import '../utils/constants.dart';
import 'camera_screen.dart';

class StudentInputScreen extends StatefulWidget {
  const StudentInputScreen({super.key});

  @override
  State<StudentInputScreen> createState() => _StudentInputScreenState();
}

class _StudentInputScreenState extends State<StudentInputScreen> {
  final _formKey = GlobalKey<FormState>();
  final _idController = TextEditingController();
  final _nameController = TextEditingController();
  final _emailController = TextEditingController();
  bool _isLoading = false;

  @override
  void initState() {
    super.initState();
    // Pre-fill the ID prefix to make input faster
    _idController.text = '1000';
    _idController.selection = TextSelection.fromPosition(
      TextPosition(offset: _idController.text.length),
    );
    
    // Listen to ID changes to auto-generate email
    _idController.addListener(_onIdChanged);
  }

  void _onIdChanged() {
    final idText = _idController.text;
    // Auto-generate email when ID is complete (9 digits starting with 1000)
    if (idText.length == 9 && idText.startsWith('1000')) {
      _emailController.text = '$idText@ku.ac.ae';
    } else if (idText.length < 9) {
      // Clear email if ID is incomplete
      _emailController.text = '';
    }
  }

  void _quickFillDemo() {
    // Quick fill with demo data for faster testing/demo
    final demoIds = ['100012345', '100067890', '100054321', '100098765'];
    final demoNames = ['Ahmed Al-Rashid', 'Fatima Al-Zahra', 'Omar Hassan', 'Sara Abdullah'];
    
    final randomIndex = DateTime.now().millisecond % demoIds.length;
    
    _idController.text = demoIds[randomIndex];
    _nameController.text = demoNames[randomIndex];
    // Email will be auto-generated by the listener
    
    setState(() {});
    
    // Show helpful message
    ScaffoldMessenger.of(context).showSnackBar(
      SnackBar(
        content: Text('Demo data filled for ${demoNames[randomIndex]}'),
        backgroundColor: Colors.green,
        duration: const Duration(seconds: 2),
      ),
    );
  }

  @override
  void dispose() {
    _idController.removeListener(_onIdChanged);
    _idController.dispose();
    _nameController.dispose();
    _emailController.dispose();
    super.dispose();
  }

  Future<void> _proceedToCamera() async {
    if (!_formKey.currentState!.validate()) {
      return;
    }

    setState(() {
      _isLoading = true;
    });

    // Create student object
    final student = Student(
      id: _idController.text.trim(),
      name: _nameController.text.trim(),
      email: _emailController.text.trim(),
    );

    // Navigate to camera screen
    if (mounted) {
      Navigator.of(context).push(
        MaterialPageRoute(
          builder: (context) => CameraScreen(student: student),
        ),
      );
    }

    setState(() {
      _isLoading = false;
    });
  }

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: const Text('Student Registration'),
        backgroundColor: Theme.of(context).primaryColor,
        foregroundColor: Colors.white,
      ),
      body: Padding(
        padding: const EdgeInsets.all(AppConstants.defaultPadding),
        child: Form(
          key: _formKey,
          child: Column(
            crossAxisAlignment: CrossAxisAlignment.stretch,
            children: [
              // Header
              const SizedBox(height: 16),
              Text(
                'Enter Student Information',
                style: Theme.of(context).textTheme.headlineSmall?.copyWith(
                  fontWeight: FontWeight.bold,
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 8),
              Text(
                'Please enter the student details for face registration',
                style: Theme.of(context).textTheme.bodyMedium,
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: 32),

              // Student ID field with auto-formatting
              TextFormField(
                controller: _idController,
                keyboardType: TextInputType.number,
                maxLength: 9,
                decoration: InputDecoration(
                  labelText: 'Student ID *',
                  hintText: '100012345',
                  prefixIcon: const Icon(Icons.badge),
                  helperText: 'Format: 1000 + 5 digits (auto-filled)',
                  counterText: '${_idController.text.length}/9',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(AppConstants.borderRadius),
                  ),
                  // Show green border when valid
                  enabledBorder: _idController.text.length == 9 && _idController.text.startsWith('1000')
                      ? OutlineInputBorder(
                          borderRadius: BorderRadius.circular(AppConstants.borderRadius),
                          borderSide: BorderSide(color: Colors.green.shade400, width: 2),
                        )
                      : OutlineInputBorder(
                          borderRadius: BorderRadius.circular(AppConstants.borderRadius),
                        ),
                ),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter student ID';
                  }
                  if (!value.startsWith('1000')) {
                    return 'Student ID must start with 1000';
                  }
                  if (value.length != 9) {
                    return 'Student ID must be exactly 9 digits (1000 + 5 digits)';
                  }
                  // Check if all characters are digits
                  if (!RegExp(r'^\d+$').hasMatch(value)) {
                    return 'Student ID must contain only numbers';
                  }
                  return null;
                },
                onChanged: (value) {
                  // Ensure it starts with 1000 and limit to numbers only
                  if (!value.startsWith('1000') && value.isNotEmpty) {
                    final newValue = '1000${value.replaceAll(RegExp(r'[^0-9]'), '')}';
                    _idController.value = TextEditingValue(
                      text: newValue.length > 9 ? newValue.substring(0, 9) : newValue,
                      selection: TextSelection.fromPosition(
                        TextPosition(offset: newValue.length > 9 ? 9 : newValue.length),
                      ),
                    );
                  } else {
                    // Remove non-numeric characters
                    final numericOnly = value.replaceAll(RegExp(r'[^0-9]'), '');
                    if (numericOnly != value) {
                      _idController.value = TextEditingValue(
                        text: numericOnly.length > 9 ? numericOnly.substring(0, 9) : numericOnly,
                        selection: TextSelection.fromPosition(
                          TextPosition(offset: numericOnly.length > 9 ? 9 : numericOnly.length),
                        ),
                      );
                    }
                  }
                  setState(() {}); // Rebuild to update border color
                },
                textInputAction: TextInputAction.next,
              ),
              const SizedBox(height: 16),

              // Name field
              TextFormField(
                controller: _nameController,
                decoration: InputDecoration(
                  labelText: 'Full Name *',
                  hintText: 'e.g., John Doe',
                  prefixIcon: const Icon(Icons.person),
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(AppConstants.borderRadius),
                  ),
                ),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter full name';
                  }
                  if (value.trim().length < 2) {
                    return 'Name must be at least 2 characters';
                  }
                  return null;
                },
                textInputAction: TextInputAction.next,
              ),
              const SizedBox(height: 16),

              // Email field (auto-generated, but editable for flexibility)
              TextFormField(
                controller: _emailController,
                keyboardType: TextInputType.emailAddress,
                decoration: InputDecoration(
                  labelText: 'Email Address *',
                  hintText: 'Auto-generated from Student ID',
                  prefixIcon: const Icon(Icons.email),
                  suffixIcon: _emailController.text.isNotEmpty
                      ? Icon(Icons.auto_awesome, color: Colors.green.shade600)
                      : null,
                  helperText: 'Auto-filled based on Student ID + @ku.ac.ae',
                  border: OutlineInputBorder(
                    borderRadius: BorderRadius.circular(AppConstants.borderRadius),
                  ),
                  // Show green border when auto-generated
                  enabledBorder: _emailController.text.endsWith('@ku.ac.ae') && _emailController.text.length > 10
                      ? OutlineInputBorder(
                          borderRadius: BorderRadius.circular(AppConstants.borderRadius),
                          borderSide: BorderSide(color: Colors.green.shade400, width: 2),
                        )
                      : OutlineInputBorder(
                          borderRadius: BorderRadius.circular(AppConstants.borderRadius),
                        ),
                ),
                validator: (value) {
                  if (value == null || value.trim().isEmpty) {
                    return 'Please enter email address';
                  }
                  // Check for ku.ac.ae domain
                  if (!value.endsWith('@ku.ac.ae')) {
                    return 'Email must end with @ku.ac.ae';
                  }
                  // Basic email validation
                  final emailRegex = RegExp(r'^[^@]+@[^@]+\.[^@]+');
                  if (!emailRegex.hasMatch(value.trim())) {
                    return 'Please enter a valid email address';
                  }
                  // Check if email matches the expected pattern for student ID
                  final expectedEmail = '${_idController.text}@ku.ac.ae';
                  if (_idController.text.length == 9 && value != expectedEmail) {
                    return 'Email should be $expectedEmail for this Student ID';
                  }
                  return null;
                },
                onFieldSubmitted: (_) => _proceedToCamera(),
              ),
              const SizedBox(height: 32),

              // Quick fill demo button for faster testing
              Row(
                children: [
                  Expanded(
                    child: OutlinedButton.icon(
                      onPressed: _quickFillDemo,
                      icon: Icon(Icons.flash_on, color: Colors.orange.shade600),
                      label: Text(
                        'Quick Fill Demo',
                        style: TextStyle(color: Colors.orange.shade600),
                      ),
                      style: OutlinedButton.styleFrom(
                        side: BorderSide(color: Colors.orange.shade300),
                        padding: const EdgeInsets.symmetric(vertical: 12),
                      ),
                    ),
                  ),
                  const SizedBox(width: 16),
                  Expanded(
                    child: ElevatedButton(
                      onPressed: _isLoading ? null : _proceedToCamera,
                      style: ElevatedButton.styleFrom(
                        padding: const EdgeInsets.symmetric(vertical: 12),
                        shape: RoundedRectangleBorder(
                          borderRadius: BorderRadius.circular(AppConstants.borderRadius),
                        ),
                      ),
                      child: _isLoading
                          ? const SizedBox(
                              height: 20,
                              width: 20,
                              child: CircularProgressIndicator(strokeWidth: 2),
                            )
                          : const Row(
                              mainAxisAlignment: MainAxisAlignment.center,
                              children: [
                                Text('Continue'),
                                SizedBox(width: 4),
                                Icon(Icons.arrow_forward, size: 18),
                              ],
                            ),
                    ),
                  ),
                ],
              ),
              const SizedBox(height: 16),

              // Instructions
              Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: Colors.blue.shade50,
                  borderRadius: BorderRadius.circular(AppConstants.borderRadius),
                  border: Border.all(color: Colors.blue.shade200),
                ),
                child: Column(
                  crossAxisAlignment: CrossAxisAlignment.start,
                  children: [
                    Row(
                      children: [
                        Icon(Icons.auto_awesome, color: Colors.blue.shade700),
                        const SizedBox(width: 8),
                        Text(
                          'Smart Input Features',
                          style: TextStyle(
                            fontWeight: FontWeight.bold,
                            color: Colors.blue.shade700,
                          ),
                        ),
                      ],
                    ),
                    const SizedBox(height: 8),
                    Text(
                      '• Student ID: Auto-starts with 1000, just add 5 more digits\n'
                      '• Email: Auto-generated as [StudentID]@ku.ac.ae\n'
                      '• Green borders indicate valid/auto-filled fields\n'
                      '• Only the student name needs manual input',
                      style: TextStyle(color: Colors.blue.shade700),
                    ),
                    const SizedBox(height: 8),
                    Row(
                      children: [
                        Icon(Icons.info_outline, color: Colors.blue.shade700, size: 16),
                        const SizedBox(width: 4),
                        Expanded(
                          child: Text(
                            'Next: Camera recording (${AppConstants.minRecordingDuration}-${AppConstants.maxRecordingDuration}s)',
                            style: TextStyle(
                              color: Colors.blue.shade700,
                              fontSize: 12,
                              fontStyle: FontStyle.italic,
                            ),
                          ),
                        ),
                      ],
                    ),
                  ],
                ),
              ),
            ],
          ),
        ),
      ),
    );
  }
}